/**
 * Plexus EHR — Ancillary Journey unified control panel.
 *
 * Renders every current ancillary service as a compact expandable ROW inside a
 * single container (no separate floating cards). Each row shows the service,
 * its current lifecycle stage, a mini-stepper, key current-episode details, and
 * a prior-test count. Expanding a row reveals the current-episode timeline,
 * service-specific prior tests (with result summaries + report/procedure-note
 * links), and the structured "Why Qualifies" evidence.
 *
 * Consumes chart.serviceEpisodes — the SINGLE per-service projection also used
 * by the Overview "Current Tests" panel, so stage never disagrees between them.
 * This component renders inner content only; PatientChartSections wraps it in a
 * SectionCard (tile chrome + eCW badge + scroll anchor).
 */

import { useState } from "react";
import { Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { ChevronDown, ChevronRight, FileText, ExternalLink, PenLine } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { JOURNEY_STAGES, JOURNEY_STAGE_ABBR } from "@/types/emr";
import type { EmrChart, EmrServiceEpisode } from "@/types/emr";
import { fmtDate } from "./profileTypes";
import { serviceVisual } from "./serviceVisuals";

const LAST_STAGE_INDEX = JOURNEY_STAGES.length - 1;

// Real canonical order/procedure note for a service (from procedure_notes).
type JourneyNote = {
  id: number; serviceType: string; noteType: string;
  generatedText: string | null; signatureStatus: string | null; signedAt: string | null;
};
// A document opened from the Journey (order/procedure note body, or prior report).
type JourneyDoc = { title: string; meta: string; body: string };

function JourneyDocDialog({ doc, onClose }: { doc: JourneyDoc | null; onClose: () => void }) {
  return (
    <Dialog open={!!doc} onOpenChange={(o) => { if (!o) onClose(); }}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto" data-testid="journey-doc-dialog">
        {doc && (
          <>
            <DialogHeader>
              <DialogTitle className="text-base flex items-center gap-2"><FileText className="w-4 h-4 text-slate-500" />{doc.title}</DialogTitle>
            </DialogHeader>
            {doc.meta && <div className="text-[11px] text-muted-foreground border-b border-slate-100 dark:border-border/40 pb-2">{doc.meta}</div>}
            <p className="text-[13px] text-slate-700 dark:text-slate-200 leading-relaxed whitespace-pre-wrap mt-1" data-testid="journey-doc-body">{doc.body}</p>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

const JOURNEY_NOTE_LABEL: Record<string, string> = { order_note: "Order Note", post_procedure_note: "Procedure Note" };
function journeyNoteMeta(n: JourneyNote): string {
  const sig = (n.signatureStatus ?? "").toLowerCase();
  if (sig === "signed") return `Generated by Plexus IQ · Signed${n.signedAt ? ` ${fmtDate(n.signedAt.slice(0, 10))}` : ""}`;
  if (sig === "ready_to_sign") return "Generated by Plexus IQ · Awaiting clinician signature";
  if (sig === "needs_signature") return "Generated by Plexus IQ · Routed for signature";
  return "Generated by Plexus IQ";
}

// A note is unsigned (physician action needed) unless its signature status is
// explicitly "signed". Unsigned notes get a Review & Sign deep link.
function isUnsignedNote(n: JourneyNote | undefined): n is JourneyNote {
  return !!n && (n.signatureStatus ?? "").toLowerCase() !== "signed";
}
// Deep link into the Physician (Clinician) Portal, targeting the EXACT signable
// note by its canonical procedure_notes.id. The portal reads these params and
// lands on Orders & Notes focused on this note (never the generic dashboard).
// Signing happens in the portal only — never inside the chart.
function portalSignHref(n: JourneyNote, screeningId: number | null): string {
  const p = new URLSearchParams({
    focus: "sign",
    noteId: String(n.id),
    noteType: n.noteType,
    serviceType: n.serviceType,
  });
  if (screeningId != null) p.set("screeningId", String(screeningId));
  return `/clinician-portal?${p.toString()}`;
}

// Stage → pill tone. Terminal stage reads as "Complete".
function stageDisplay(ep: EmrServiceEpisode): { label: string; color: string; bg: string } {
  if (ep.stageIndex >= LAST_STAGE_INDEX) return { label: "Complete", color: "#16A36A", bg: "#EAF8F1" };
  if (/scheduled/i.test(ep.stage)) return { label: ep.stage, color: "#2459E0", bg: "#EDF3FF" };
  if (/outreach/i.test(ep.stage)) return { label: ep.stage, color: "#2459E0", bg: "#EDF3FF" };
  if (/qualified|approved/i.test(ep.stage)) return { label: ep.stage, color: "#667085", bg: "#F1F5F9" };
  return { label: ep.stage, color: "#3169E8", bg: "#EDF3FF" };
}

// One-line collapsed detail summarizing the current episode state.
function detailLine(ep: EmrServiceEpisode): string {
  const a = ep.appointment;
  if (a && (a.status === "scheduled") && a.date) {
    return [fmtDate((a.date || "").slice(0, 10)), a.time, ep.orderStatus ? `Order ${ep.orderStatus}` : null].filter(Boolean).join(" · ");
  }
  if (ep.stageIndex >= LAST_STAGE_INDEX) {
    return [a?.date ? `DOS ${fmtDate((a.date || "").slice(0, 10))}` : null, ep.reportStatus ? `Report ${ep.reportStatus}` : "Report Final", ep.procedureNoteStatus ? `Procedure ${ep.procedureNoteStatus}` : "Procedure Signed"].filter(Boolean).join(" · ");
  }
  if (/outreach/i.test(ep.stage)) {
    return [ep.owner ? `Owner ${ep.owner}` : null, ep.nextAction].filter(Boolean).join(" · ");
  }
  return ep.nextAction ?? "";
}

// ─── Compact dot strip (collapsed row) ────────────────────────────────────
function StageStrip({ index }: { index: number }) {
  return (
    <div className="flex items-center" style={{ minWidth: 140 }}>
      {JOURNEY_STAGES.map((_, i) => {
        const done = i < index;
        const active = i === index;
        return (
          <div key={i} className="flex items-center" style={{ flex: i < LAST_STAGE_INDEX ? "1 1 0%" : "0 0 auto" }}>
            <span
              className="rounded-full shrink-0"
              style={{ width: active ? 9 : 7, height: active ? 9 : 7, background: done ? "#16A36A" : active ? "#3169E8" : "#E2E8F0" }}
              title={JOURNEY_STAGES[i]}
            />
            {i < LAST_STAGE_INDEX && <span className="flex-1 h-[2px] mx-0.5" style={{ background: done ? "#16A36A" : "#E2E8F0" }} />}
          </div>
        );
      })}
    </div>
  );
}

// ─── Full labeled stepper (expanded) ──────────────────────────────────────
function MiniStepper({ index }: { index: number }) {
  return (
    <div>
      <div className="flex items-center mb-1">
        {JOURNEY_STAGES.map((_, i) => {
          const done = i < index;
          const active = i === index;
          return (
            <div key={i} className="flex items-center" style={{ flex: i < LAST_STAGE_INDEX ? "1 1 0%" : "0 0 auto" }}>
              <span
                className="rounded-full shrink-0 flex items-center justify-center text-[7px] font-bold"
                style={{ width: 12, height: 12, background: done ? "#16A36A" : active ? "#3169E8" : "#E2E8F0", color: done || active ? "#fff" : "#98A2B3" }}
              >
                {done ? "✓" : ""}
              </span>
              {i < LAST_STAGE_INDEX && <span className="flex-1 h-[2px] mx-0.5" style={{ background: done ? "#16A36A" : "#E2E8F0" }} />}
            </div>
          );
        })}
      </div>
      <div className="flex">
        {JOURNEY_STAGE_ABBR.map((s, i) => (
          <span key={s} className="text-center leading-none whitespace-nowrap" style={{ flex: i < LAST_STAGE_INDEX ? "1 1 0%" : "0 0 auto", fontSize: "8.5px", color: i < index ? "#16A36A" : i === index ? "#3169E8" : "#98A2B3", fontWeight: i === index ? 700 : 500 }}>
            {s}
          </span>
        ))}
      </div>
    </div>
  );
}

function KVRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-baseline gap-2 text-xs">
      <span className="text-[10px] uppercase tracking-wide text-slate-400 w-24 shrink-0">{label}</span>
      <span className="text-slate-700 dark:text-slate-200">{value}</span>
    </div>
  );
}

function ActionLink({ label, disabled, onClick }: { label: string; disabled?: boolean; onClick?: () => void }) {
  return (
    <button
      disabled={disabled}
      onClick={onClick}
      className={`text-[11px] font-medium inline-flex items-center gap-1 ${disabled ? "text-slate-300 cursor-not-allowed" : "text-blue-600 hover:underline"}`}
    >
      {label}
    </button>
  );
}

// ─── Why Qualifies (structured, inline) ───────────────────────────────────
function WhyQualifies({ ep }: { ep: EmrServiceEpisode }) {
  const r = ep.reasoning;
  if (!r) return <p className="text-xs text-slate-500">No qualification detail available.</p>;
  const factors = r.qualifyingFactors ?? [];
  const icd = r.icd10Codes ?? [];
  const pearls = r.pearls ?? [];
  return (
    <div className="space-y-2 text-xs">
      {factors.length > 0 && (
        <div>
          <div className="text-[9px] font-bold uppercase tracking-wide text-slate-400 mb-1">Clinical Justification</div>
          <ul className="list-disc list-inside space-y-0.5 text-slate-600 dark:text-slate-300">{factors.slice(0, 6).map((f, i) => <li key={i}>{f}</li>)}</ul>
        </div>
      )}
      {icd.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {icd.map((c, i) => <span key={i} className="px-1.5 py-0.5 rounded text-[10px] font-mono" style={{ background: "#F1F5F9", color: "#475569" }}>{c}</span>)}
        </div>
      )}
      {r.confidence && <div className="text-[11px] text-slate-500">Confidence: <span className="font-medium capitalize text-slate-700 dark:text-slate-200">{r.confidence}</span></div>}
      {r.patientTalkingPoints && (
        <div>
          <div className="text-[9px] font-bold uppercase tracking-wide text-slate-400 mb-1">Patient Talking Points</div>
          <p className="text-slate-600 dark:text-slate-300 leading-snug">{r.patientTalkingPoints}</p>
        </div>
      )}
      {pearls.length > 0 && (
        <div>
          <div className="text-[9px] font-bold uppercase tracking-wide text-slate-400 mb-1">Pearls</div>
          <ul className="list-disc list-inside space-y-0.5 text-slate-600 dark:text-slate-300">{pearls.slice(0, 4).map((p, i) => <li key={i}>{p}</li>)}</ul>
        </div>
      )}
    </div>
  );
}

// ─── Prior tests (service-specific, inline) ───────────────────────────────
// Reports open directly here (Ancillary Journey → Previous Tests) — the report
// body is the canonical result summary for that prior performance.
function PriorTests({ ep, onOpen }: { ep: EmrServiceEpisode; onOpen: (d: JourneyDoc) => void }) {
  const prior = ep.priorTests ?? [];
  if (prior.length === 0) return <p className="text-xs text-slate-500">No prior tests.</p>;
  return (
    <div className="space-y-2.5">
      {prior.map((p, i) => {
        const dateLabel = fmtDate((p.dateOfService || "").slice(0, 10));
        const body = p.resultSummary || "Report on file.";
        return (
          <div key={i} className="text-xs" data-testid={`prior-test-${ep.serviceKey}-${i}`}>
            <div className="flex items-center justify-between gap-2">
              <span className="font-semibold text-slate-700 dark:text-slate-200">{dateLabel}</span>
              <span className="flex items-center gap-3">
                {p.reportAvailable && (
                  <button
                    onClick={() => onOpen({ title: `${p.serviceName ?? ep.serviceName} Report — ${dateLabel}`, meta: [p.payer ?? null, "Final report"].filter(Boolean).join(" · "), body })}
                    className="text-[11px] text-blue-600 hover:underline inline-flex items-center gap-0.5"
                    data-testid={`prior-report-${ep.serviceKey}-${i}`}
                  ><FileText className="w-3 h-3" />Report</button>
                )}
              </span>
            </div>
            <div className="text-slate-600 dark:text-slate-300 leading-snug">{p.resultSummary || `${p.serviceName ?? ep.serviceName}`}{p.payer ? ` · ${p.payer}` : ""}</div>
          </div>
        );
      })}
    </div>
  );
}

// ─── One service row (collapsed + expanded) ───────────────────────────────
function ServiceRow({ ep, notes, screeningId, onOpen }: { ep: EmrServiceEpisode; notes: JourneyNote[]; screeningId: number | null; onOpen: (d: JourneyDoc) => void }) {
  const [open, setOpen] = useState(false);
  const [showWhy, setShowWhy] = useState(false);
  const orderNote = notes.find((n) => n.noteType === "order_note" && n.generatedText);
  const procedureNote = notes.find((n) => n.noteType === "post_procedure_note" && n.generatedText);
  const vis = serviceVisual(ep.serviceName);
  const Icon = vis.Icon;
  const sd = stageDisplay(ep);
  const priorCount = ep.priorTests?.length ?? 0;

  return (
    <div data-testid={`journey-row-${ep.serviceKey}`}>
      {/* Collapsed row */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-3 px-3.5 py-3 text-left hover:bg-slate-50 dark:hover:bg-muted/40 transition-colors"
        data-testid={`journey-toggle-${ep.serviceKey}`}
      >
        <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style={{ background: vis.bg }}>
          <Icon className="w-5 h-5" style={{ color: vis.color }} />
        </div>
        <div className="min-w-0" style={{ width: 200 }}>
          <div className="text-[13px] font-bold truncate" style={{ color: "#0F172A" }}>{ep.serviceName}</div>
          <div className="text-[11px] text-slate-500 truncate">{detailLine(ep)}</div>
        </div>
        <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded-full shrink-0" style={{ color: sd.color, background: sd.bg }}>{sd.label}</span>
        <div className="flex-1 hidden lg:block px-2"><StageStrip index={ep.stageIndex} /></div>
        <span className="text-[11px] text-slate-500 shrink-0 w-16 text-right">{priorCount > 0 ? `${priorCount} prior` : "No prior"}</span>
        {open ? <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" /> : <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />}
      </button>

      {/* Expanded */}
      {open && (
        <div className="px-3.5 pb-4 pt-1 bg-slate-50/40 dark:bg-muted/20">
          <div className="lg:hidden mb-3"><MiniStepper index={ep.stageIndex} /></div>
          <div className="hidden lg:block mb-3"><MiniStepper index={ep.stageIndex} /></div>

          {/* Current episode details */}
          <div className="rounded-lg bg-white dark:bg-card border border-slate-200/70 dark:border-border/50 p-3 mb-3">
            <div className="text-[9px] font-bold uppercase tracking-wide text-slate-400 mb-2">Current Journey</div>
            <div className="space-y-1">
              {ep.appointment?.date && <KVRow label="Appointment" value={`${fmtDate((ep.appointment.date || "").slice(0, 10))}${ep.appointment.time ? ` · ${ep.appointment.time}` : ""}${ep.appointment.facility ? ` · ${ep.appointment.facility}` : ""}`} />}
              {ep.orderStatus && <KVRow label="Order" value={ep.orderStatus} />}
              {ep.screeningStatus && <KVRow label="Screening" value={ep.screeningStatus} />}
              {ep.reportStatus && <KVRow label="Report" value={ep.reportStatus} />}
              {ep.owner && <KVRow label="Owner" value={ep.owner} />}
              {ep.nextAction && <KVRow label="Next action" value={ep.nextAction} />}
            </div>
            <div className="flex items-center gap-4 mt-3 pt-2 border-t border-slate-100 dark:border-border/40">
              <button onClick={() => setShowWhy(!showWhy)} className="text-[11px] font-medium text-blue-600 hover:underline">Why Qualifies</button>
              {orderNote && (
                <ActionLink label="Open Order Note" onClick={() => onOpen({ title: `Order Note — ${ep.serviceName}`, meta: journeyNoteMeta(orderNote), body: orderNote.generatedText ?? "" })} />
              )}
              {isUnsignedNote(orderNote) && (
                <Link href={portalSignHref(orderNote, screeningId)}>
                  <button className="text-[11px] font-medium inline-flex items-center gap-1 text-amber-700 hover:underline" data-testid={`review-sign-order_note-${ep.serviceKey}`}>
                    <PenLine className="w-3 h-3" />Review &amp; Sign
                  </button>
                </Link>
              )}
              {procedureNote && (
                <ActionLink label="Open Procedure Note" onClick={() => onOpen({ title: `Procedure Note — ${ep.serviceName}`, meta: journeyNoteMeta(procedureNote), body: procedureNote.generatedText ?? "" })} />
              )}
              {isUnsignedNote(procedureNote) && (
                <Link href={portalSignHref(procedureNote, screeningId)}>
                  <button className="text-[11px] font-medium inline-flex items-center gap-1 text-amber-700 hover:underline" data-testid={`review-sign-procedure_note-${ep.serviceKey}`}>
                    <PenLine className="w-3 h-3" />Review &amp; Sign
                  </button>
                </Link>
              )}
            </div>
            {showWhy && <div className="mt-3 pt-2 border-t border-slate-100 dark:border-border/40"><WhyQualifies ep={ep} /></div>}
          </div>

          {/* Previous tests (service-specific, historical) */}
          <div className="rounded-lg border border-slate-200/70 dark:border-border/50 p-3" style={{ background: "#FAFBFC" }}>
            <div className="text-[9px] font-bold uppercase tracking-wide text-slate-400 mb-2">Previous Tests {priorCount > 0 ? `(${priorCount})` : ""}</div>
            <PriorTests ep={ep} onOpen={onOpen} />
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Summary line ─────────────────────────────────────────────────────────
function summarize(episodes: EmrServiceEpisode[]): string {
  const buckets: Record<string, number> = {};
  for (const ep of episodes) {
    const label = ep.stageIndex >= LAST_STAGE_INDEX ? "Completed" : ep.stage;
    buckets[label] = (buckets[label] ?? 0) + 1;
  }
  return Object.entries(buckets).map(([k, v]) => `${v} ${k}`).join(" · ");
}

// ─── Inner content (wrapped by SectionCard in PatientChartSections) ───────
export function PlexusEhr({ chart }: { chart: EmrChart }) {
  const episodes = chart.serviceEpisodes ?? [];
  const screeningId = chart.patientScreeningId ?? null;
  const [openDoc, setOpenDoc] = useState<JourneyDoc | null>(null);

  // Real canonical order/procedure notes so "Open Order/Procedure Note" opens
  // the actual generated note body (no dead buttons).
  const { data: notes = [] } = useQuery<JourneyNote[]>({
    queryKey: ["/api/procedure-notes", { patientScreeningId: screeningId }],
    queryFn: async () => {
      const res = await fetch(`/api/procedure-notes?patientScreeningId=${screeningId}`, { credentials: "include" });
      if (!res.ok) return [];
      const rows = await res.json();
      return Array.isArray(rows) ? rows : [];
    },
    enabled: screeningId != null,
  });
  const notesByService = new Map<string, JourneyNote[]>();
  for (const n of notes) {
    const arr = notesByService.get(n.serviceType); if (arr) arr.push(n); else notesByService.set(n.serviceType, [n]);
  }

  if (episodes.length === 0) {
    return <p className="text-sm text-slate-500" data-testid="journey-empty">No active ancillary services. Run Plexus IQ to qualify services.</p>;
  }
  return (
    <div data-testid="ancillary-journey">
      <div className="flex items-center justify-between gap-3 mb-3">
        <div>
          <div className="text-[11px] font-bold uppercase tracking-wide text-slate-500">Current Ancillary Journey</div>
          <div className="text-[11px] text-slate-500 mt-0.5">{episodes.length} active service{episodes.length === 1 ? "" : "s"} · {summarize(episodes)}</div>
        </div>
      </div>
      <div className="rounded-xl border border-slate-200/80 dark:border-border/60 divide-y divide-slate-100 dark:divide-border/40 overflow-hidden">
        {episodes.map((ep) => <ServiceRow key={ep.serviceKey} ep={ep} notes={notesByService.get(ep.serviceName) ?? []} screeningId={screeningId} onOpen={setOpenDoc} />)}
      </div>
      <JourneyDocDialog doc={openDoc} onClose={() => setOpenDoc(null)} />
    </div>
  );
}
