// FHIR Import Pipeline — main orchestrator
//
// Flow:
//   1. Resolve export timestamp (latest or explicit)
//   2. Read NDJSON files from S3
//   3. Parse into FhirPatientBundle[] (grouped by patient FHIR id)
//   4. Create a screening_batches row for this import run
//   5. For each patient bundle:
//      a. Extract MRN
//      b. Check patient_directory for existing row (mrn + clinic_id match)
//      c. If found → UPDATE demographics + clinical data
//      d. If not → INSERT (plexusId auto-generated by DB trigger)
//      e. INSERT a patient_screenings row in the new batch
//   6. Update batch patient_count
//   7. If autoQualify → call startBatchAnalysis (background, non-blocking)
//   8. Return ImportResult with stats
//
// PHI-safe: patient names, DOBs, and clinical details are never logged.
// Only counts, S3 keys, batch/job IDs, and error messages appear in logs.

import { eq, and } from "drizzle-orm";
import { db } from "../../db";
import { storage } from "../../storage";
import { clinics } from "@shared/schema/clinics";
import { patientDirectory } from "@shared/schema/patientDirectory";
import { patientScreenings } from "@shared/schema/screening";
import { startBatchAnalysis } from "../batchAnalysisRunner";
import { getLatestExportTimestamp, readAllNdjsonFiles } from "./fhirS3Reader";
import { parseFhirNdjsonFiles } from "./fhirNdjsonParser";
import { mapFhirToPatientDirectory, mapFhirToScreening } from "./fhirPatientMapper";
import type { FhirImportOptions, FhirImportResult, FhirImportStats } from "./types";

// ─── Helpers ─────────────────────────────────────────────────────────────

function buildBatchName(clinicName: string, timestamp: string): string {
  // Format: "Taylor Family Practice — FHIR Import 2026-08-23"
  // Use the timestamp folder name when it looks like a date, otherwise today.
  const datePart = timestamp.slice(0, 10).replace(/[^0-9-]/g, "") || new Date().toISOString().slice(0, 10);
  return `${clinicName} — FHIR Import ${datePart}`;
}

// ─── Orchestrator ─────────────────────────────────────────────────────────

export async function runFhirImport(
  options: FhirImportOptions,
): Promise<FhirImportResult> {
  const {
    groupId,
    clinicId,
    clinicSlug,
    clinicName,
    autoQualify,
    dryRun = false,
  } = options;

  const stats: FhirImportStats = {
    totalPatientBundles: 0,
    inserted: 0,
    updated: 0,
    skipped: 0,
    errors: 0,
    batchId: null,
    analysisJobId: null,
  };

  // ── Step 1: resolve export timestamp ────────────────────────────────────
  let timestamp = options.timestamp && options.timestamp !== "latest"
    ? options.timestamp
    : null;

  if (!timestamp) {
    console.log(`[fhirImport] resolving latest export timestamp for group ${groupId}`);
    timestamp = await getLatestExportTimestamp(groupId);
    if (!timestamp) {
      return {
        ok: false,
        stats,
        message: `No export found in S3 for group ${groupId}`,
        error: "No export timestamp found",
      };
    }
  }

  console.log(`[fhirImport] using timestamp: ${timestamp} for group ${groupId}`);

  // ── Step 2: read NDJSON files from S3 ───────────────────────────────────
  let ndjsonFiles: Array<{ key: string; content: string }>;
  try {
    ndjsonFiles = await readAllNdjsonFiles(groupId, timestamp);
  } catch (err: any) {
    return {
      ok: false,
      stats,
      message: "Failed to read NDJSON files from S3",
      error: err?.message ?? String(err),
    };
  }

  if (ndjsonFiles.length === 0) {
    return {
      ok: false,
      stats,
      message: `No NDJSON files found at s3://${process.env.FHIR_IMPORT_S3_BUCKET ?? "fhir-bulk-exp"}/${groupId}/${timestamp}/`,
      error: "Empty export",
    };
  }

  console.log(`[fhirImport] downloaded ${ndjsonFiles.length} NDJSON file(s)`);

  // ── Step 3: parse into bundles ───────────────────────────────────────────
  const { bundles, totalLines, parseErrors } = parseFhirNdjsonFiles(ndjsonFiles);
  stats.totalPatientBundles = bundles.size;

  console.log(
    `[fhirImport] parsed ${totalLines} lines → ${bundles.size} patient bundle(s), ${parseErrors} parse error(s)`,
  );

  if (bundles.size === 0) {
    return {
      ok: false,
      stats,
      message: "Parsed 0 patient bundles from NDJSON — nothing to import",
      error: "No patients found",
    };
  }

  // ── Dry-run exits here — no DB writes ────────────────────────────────────
  if (dryRun) {
    return {
      ok: true,
      stats,
      message: `[DRY RUN] Would import ${bundles.size} patient bundle(s) (${parseErrors} parse error(s)) from ${ndjsonFiles.length} file(s)`,
    };
  }

  // ── Step 3b: ensure clinic row exists ─────────────────────────────────────
  // The clinics table may not have been seeded yet. Insert-or-ignore the
  // configured clinic so the screening_batches FK constraint doesn't fail.
  try {
    const existing = await db.select().from(clinics).where(eq(clinics.id, clinicId)).limit(1);
    if (existing.length === 0) {
      await db.insert(clinics).values({
        id: clinicId,
        name: clinicName,
        slug: clinicSlug,
      });
      console.log(`[fhirImport] seeded clinic row: id=${clinicId}, name="${clinicName}"`);
    }
  } catch (seedErr: any) {
    console.warn(`[fhirImport] clinic seed warning (non-fatal): ${seedErr?.message}`);
  }

  // ── Step 4: create screening_batches row ─────────────────────────────────
  let batch: Awaited<ReturnType<typeof storage.createScreeningBatch>>;
  try {
    batch = await storage.createScreeningBatch({
      clinicId,
      name: buildBatchName(clinicName, timestamp),
      patientCount: 0,
      status: "draft",
      facility: clinicName,
      scheduleDate: null,
      importKind: "full",
    });
    stats.batchId = batch.id;
    console.log(`[fhirImport] created batch ${batch.id} for clinic ${clinicId}`);
  } catch (err: any) {
    return {
      ok: false,
      stats,
      message: "Failed to create screening batch",
      error: err?.message ?? String(err),
    };
  }

  // ── Step 5: upsert patient_directory + insert patient_screenings ─────────
  const screeningRows: Array<(typeof patientScreenings.$inferInsert)> = [];

  for (const [fhirPatientId, bundle] of bundles) {
    try {
      const directoryRow = mapFhirToPatientDirectory(bundle, clinicSlug);
      const mrn = directoryRow.mrn;

      // Dedup: look up existing patient_directory row by MRN + clinic_id
      let existingDirectoryId: number | null = null;

      if (mrn) {
        const existing = await db
          .select({ id: patientDirectory.id })
          .from(patientDirectory)
          .where(
            and(
              eq(patientDirectory.mrn, mrn),
              eq(patientDirectory.clinicId, clinicSlug),
            ),
          )
          .limit(1);

        if (existing.length > 0) {
          existingDirectoryId = existing[0].id;
        }
      }

      if (existingDirectoryId !== null) {
        // UPDATE existing patient_directory row (demographics refresh)
        await db
          .update(patientDirectory)
          .set({
            firstName: directoryRow.firstName,
            lastName: directoryRow.lastName,
            dob: directoryRow.dob,
            gender: directoryRow.gender,
            phone: directoryRow.phone,
            email: directoryRow.email,
            facilityId: directoryRow.facilityId,
            status: "active",
            updatedAt: new Date(),
          })
          .where(eq(patientDirectory.id, existingDirectoryId));
        stats.updated += 1;
      } else {
        // INSERT new patient_directory row — plexusId is NOT NULL in the schema
        // but is generated by a DB trigger on insert. We supply a temporary empty
        // string that the trigger immediately overwrites before the row is visible.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await db.insert(patientDirectory).values({ ...directoryRow, plexusId: "" } as any);
        stats.inserted += 1;
      }

      // Always create a new screening row in this batch (represents a new
      // qualification run, even for returning patients)
      const screeningRow = mapFhirToScreening(bundle, clinicId, batch.id, clinicName);
      screeningRows.push(screeningRow);
    } catch (err: any) {
      // Per-patient error — log FHIR id only (PHI-safe), continue
      console.error(
        `[fhirImport] failed to process FHIR patient ${fhirPatientId}: ${err?.message ?? err}`,
      );
      stats.errors += 1;
    }
  }

  // ── Bulk insert patient_screenings ───────────────────────────────────────
  if (screeningRows.length > 0) {
    try {
      // Insert in chunks of 500 to stay within pg parameter limits
      const CHUNK_SIZE = 500;
      for (let i = 0; i < screeningRows.length; i += CHUNK_SIZE) {
        const chunk = screeningRows.slice(i, i + CHUNK_SIZE);
        await db.insert(patientScreenings).values(chunk);
      }
      console.log(`[fhirImport] inserted ${screeningRows.length} screening row(s) into batch ${batch.id}`);
    } catch (err: any) {
      console.error(`[fhirImport] bulk screening insert failed: ${err?.message ?? err}`);
      // Continue — batch exists, update count with what we have
    }
  }

  // ── Step 6: update batch patient_count ──────────────────────────────────
  const finalCount = stats.inserted + stats.updated;
  await storage.updateScreeningBatch(batch.id, { patientCount: finalCount });

  // ── Step 7: auto-qualify ─────────────────────────────────────────────────
  if (autoQualify && screeningRows.length > 0) {
    try {
      // startBatchAnalysis is fire-and-forget — it creates a job row and
      // returns immediately; the AI loop runs as a background task.
      const jobResult = await startBatchAnalysis(batch.id, null, {});
      stats.analysisJobId = jobResult.jobId;
      console.log(
        `[fhirImport] triggered Plexus IQ analysis job ${jobResult.jobId} for batch ${batch.id} (${jobResult.totalPatients} patient(s))`,
      );
    } catch (err: any) {
      // Non-fatal — import succeeded; qualification can be retried manually
      console.error(
        `[fhirImport] failed to start batch analysis for batch ${batch.id}: ${err?.message ?? err}`,
      );
    }
  }

  return {
    ok: true,
    stats,
    message:
      `Imported ${stats.totalPatientBundles} patient bundle(s): ` +
      `${stats.inserted} new, ${stats.updated} updated, ${stats.errors} error(s). ` +
      `Batch ID: ${batch.id}.` +
      (stats.analysisJobId ? ` Analysis job: ${stats.analysisJobId}.` : ""),
  };
}
