// detectorRegistry — Phase 3 PR 3.1.
//
// Declarative registry of every exception detector. Each entry
// describes: category, default severity, default owner role, the
// admin_settings key that overrides the threshold, and a friendly
// title + explanation template.
//
// New detectors (PR 3.6, 3.7) extend this list. The engine
// (PR 3.2) consumes the registry to know which checks to run.

import type { DetectorDefinition, ExceptionType } from "@shared/contracts/exceptionIntelligence";

export const DETECTOR_REGISTRY: DetectorDefinition[] = [
  // ── Engagement / call ────────────────────────────────────────────────
  {
    exceptionType: "callback_overdue",
    category: "engagement",
    defaultSeverity: "medium",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "callback_overdue_threshold_hours",
    defaultThresholdValue: 2,
    thresholdUnit: "hours",
    title: "Callback overdue",
    explanationTemplate: "Callback was due at {nextActionAt}; now overdue by {hoursOverdue}h.",
  },
  {
    exceptionType: "lvm_followup_overdue",
    category: "engagement",
    defaultSeverity: "medium",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "lvm_stale_threshold_hours",
    defaultThresholdValue: 8,
    thresholdUnit: "hours",
    title: "LVM follow-up overdue",
    explanationTemplate: "Last LVM at {lastAttemptAt}; threshold {thresholdValue}h exceeded.",
  },
  {
    exceptionType: "no_answer_followup_overdue",
    category: "engagement",
    defaultSeverity: "medium",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "no_answer_stale_threshold_hours",
    defaultThresholdValue: 8,
    thresholdUnit: "hours",
    title: "No-answer follow-up overdue",
    explanationTemplate: "Last no-answer at {lastAttemptAt}; threshold {thresholdValue}h exceeded.",
  },
  {
    exceptionType: "unable_to_reach_threshold_met",
    category: "engagement",
    defaultSeverity: "high",
    defaultOwnerRole: "manager_review",
    thresholdSettingKey: "unable_to_reach_attempt_threshold",
    defaultThresholdValue: 6,
    thresholdUnit: "attempts",
    title: "Unable to reach — threshold met",
    explanationTemplate: "Call attempt count {callAttemptCount} ≥ {thresholdValue}.",
  },
  {
    exceptionType: "ready_to_schedule_stale",
    category: "engagement",
    defaultSeverity: "medium",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "ready_to_schedule_stale_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Ready to schedule — stale",
    explanationTemplate: "Marked ready to schedule {lastUpdateHoursAgo}h ago; still no schedule event.",
  },
  {
    exceptionType: "stale_queue_item",
    category: "engagement",
    defaultSeverity: "low",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "stale_queue_item_threshold_hours",
    defaultThresholdValue: 48,
    thresholdUnit: "hours",
    title: "Stale queue item",
    explanationTemplate: "Case sat in queue with no progress for {hoursStale}h.",
  },

  // ── Document / ACS ───────────────────────────────────────────────────
  {
    exceptionType: "report_missing",
    category: "document",
    defaultSeverity: "medium",
    defaultOwnerRole: "acs",
    thresholdSettingKey: "missing_report_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Report missing",
    explanationTemplate: "Procedure complete at {procedureCompletedAt}; report not uploaded after {thresholdValue}h.",
  },
  {
    exceptionType: "order_note_missing",
    category: "document",
    defaultSeverity: "medium",
    defaultOwnerRole: "acs",
    thresholdSettingKey: "missing_order_note_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Order note missing",
    explanationTemplate: "Order note has been missing for {hoursMissing}h.",
  },
  {
    exceptionType: "procedure_note_missing",
    category: "document",
    defaultSeverity: "medium",
    defaultOwnerRole: "acs",
    thresholdSettingKey: "missing_procedure_note_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Procedure note missing",
    explanationTemplate: "Procedure note has been missing for {hoursMissing}h after procedure completion.",
  },
  {
    exceptionType: "physician_signature_pending",
    category: "document",
    defaultSeverity: "high",
    defaultOwnerRole: "acs",
    thresholdSettingKey: "physician_signature_pending_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Physician signature pending",
    explanationTemplate: "Order note present but physician signature pending for {hoursPending}h.",
  },
  {
    exceptionType: "billing_readiness_blocked",
    category: "document",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "billing_readiness_blocked_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Billing readiness blocked",
    explanationTemplate: "Readiness check not ready for {hoursBlocked}h.",
  },
  {
    exceptionType: "insurance_verification_pending",
    category: "document",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "insurance_verification_pending_threshold_hours",
    defaultThresholdValue: 48,
    thresholdUnit: "hours",
    title: "Insurance verification pending",
    explanationTemplate: "Insurance verification has been pending for {hoursPending}h.",
  },
  {
    exceptionType: "duplicate_patient_risk",
    category: "document",
    defaultSeverity: "low",
    defaultOwnerRole: "admin",
    thresholdSettingKey: "duplicate_patient_risk_window_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Duplicate patient risk",
    explanationTemplate: "Potential duplicate of {otherPatient} detected within window.",
  },
  {
    exceptionType: "missing_patient_contact",
    category: "document",
    defaultSeverity: "low",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "missing_patient_contact_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Missing patient contact",
    explanationTemplate: "No phone or email on record; outreach blocked.",
  },

  // ── Scheduling ───────────────────────────────────────────────────────
  {
    exceptionType: "scheduling_delay",
    category: "scheduling",
    defaultSeverity: "medium",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "scheduling_delay_threshold_hours",
    defaultThresholdValue: 48,
    thresholdUnit: "hours",
    title: "Scheduling delay",
    explanationTemplate: "Ready to schedule {hoursDelayed}h ago; no scheduled event yet.",
  },
  {
    exceptionType: "no_show_followup_due",
    category: "scheduling",
    defaultSeverity: "high",
    defaultOwnerRole: "pcs",
    thresholdSettingKey: "no_show_followup_threshold_hours",
    defaultThresholdValue: 4,
    thresholdUnit: "hours",
    title: "No-show follow-up due",
    explanationTemplate: "No-show recorded at {noShowAt}; follow-up window {thresholdValue}h elapsed.",
  },

  // ── Billing ──────────────────────────────────────────────────────────
  {
    exceptionType: "invoice_readiness_blocked",
    category: "billing",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "invoice_readiness_blocked_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Invoice readiness blocked",
    explanationTemplate: "Snapshot has been blocked for {hoursBlocked}h: {blockers}.",
  },
  {
    exceptionType: "invoice_batch_stale",
    category: "billing",
    defaultSeverity: "low",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "invoice_batch_stale_threshold_days",
    defaultThresholdValue: 7,
    thresholdUnit: "days",
    title: "Invoice batch stale",
    explanationTemplate: "Batch #{batchId} sat in {batchStatus} for {daysStale}d.",
  },
  {
    exceptionType: "invoice_draft_stale",
    category: "billing",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "invoice_draft_stale_threshold_days",
    defaultThresholdValue: 3,
    thresholdUnit: "days",
    title: "Invoice draft stale",
    explanationTemplate: "Draft #{invoiceId} in pending_review for {daysStale}d.",
  },
  {
    exceptionType: "invoice_approval_stale",
    category: "billing",
    defaultSeverity: "medium",
    defaultOwnerRole: "admin",
    thresholdSettingKey: "invoice_approval_stale_threshold_days",
    defaultThresholdValue: 2,
    thresholdUnit: "days",
    title: "Invoice approval stale",
    explanationTemplate: "Invoice #{invoiceId} approved but not delivered for {daysStale}d.",
  },
  {
    exceptionType: "invoice_delivery_failed",
    category: "billing",
    defaultSeverity: "high",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "invoice_delivery_failed_severity",
    defaultThresholdValue: 0,
    thresholdUnit: "count",
    title: "Invoice delivery failed",
    explanationTemplate: "Delivery of invoice #{invoiceId} failed at {failedAt}.",
  },
  {
    exceptionType: "missing_invoice_recipient",
    category: "billing",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "missing_invoice_recipient_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Missing invoice recipient",
    explanationTemplate: "Invoice #{invoiceId} approved but no recipient is resolvable from policy.",
  },
  {
    exceptionType: "payment_overdue",
    category: "billing",
    defaultSeverity: "medium",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "payment_overdue_threshold_days",
    defaultThresholdValue: 0,
    thresholdUnit: "days",
    title: "Payment overdue",
    explanationTemplate: "Invoice #{invoiceId} balance {totalBalance} past due {daysOverdue}d.",
  },
  {
    exceptionType: "denial_followup_due",
    category: "billing",
    defaultSeverity: "high",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "denial_followup_threshold_days",
    defaultThresholdValue: 3,
    thresholdUnit: "days",
    title: "Denial follow-up due",
    explanationTemplate: "Open denial #{denialId} ({denialCode}) older than {thresholdValue}d.",
  },
  {
    exceptionType: "disputed_invoice",
    category: "billing",
    defaultSeverity: "high",
    defaultOwnerRole: "admin",
    thresholdSettingKey: "disputed_invoice_threshold_hours",
    defaultThresholdValue: 24,
    thresholdUnit: "hours",
    title: "Invoice in dispute",
    explanationTemplate: "Invoice #{invoiceId} has a dispute_hold adjustment.",
  },
  {
    exceptionType: "remittance_missing",
    category: "billing",
    defaultSeverity: "low",
    defaultOwnerRole: "biller",
    thresholdSettingKey: "remittance_missing_threshold_days",
    defaultThresholdValue: 7,
    thresholdUnit: "days",
    title: "Remittance missing",
    explanationTemplate: "Invoice #{invoiceId} marked sent but no remittance event in {daysMissing}d.",
  },
  {
    exceptionType: "high_balance_aging",
    category: "billing",
    defaultSeverity: "high",
    defaultOwnerRole: "admin",
    thresholdSettingKey: "high_balance_aging_threshold_days",
    defaultThresholdValue: 30,
    thresholdUnit: "days",
    title: "High-balance aging",
    explanationTemplate: "Invoice #{invoiceId} balance {totalBalance} aged {daysAging}d.",
  },
];

export function getDetectorByType(type: ExceptionType): DetectorDefinition | undefined {
  return DETECTOR_REGISTRY.find((d) => d.exceptionType === type);
}

export function listDetectorsByCategory(category: DetectorDefinition["category"]): DetectorDefinition[] {
  return DETECTOR_REGISTRY.filter((d) => d.category === category);
}
