// DEMO MOCK DATA — Imaging Central.
//
// Replace with API-backed queries when endpoints are available. Likely
// shape:
//   GET /api/imaging-central/work-queue       → ImagingTask[]
//   GET /api/imaging-central/coverage         → ImagingCoverageRow[]
//   GET /api/imaging-central/technicians      → ImagingTechnician[]
//
// The page also derives a readiness list and KPI band from the work
// queue; both stay client-side until a server endpoint exists.

import type {
  ImagingCoverageRow,
  ImagingStatus,
  ImagingTask,
  ImagingTechnician,
  UltrasoundType,
} from "./types";

export const IMAGING_CENTRAL_CLINICS = [
  "Northgate Cardiology",
  "Lakeside Family Medicine",
  "Summit Vascular Institute",
  "Harbor Internal Medicine",
] as const;

export const IMAGING_CENTRAL_TECHNICIANS = [
  "Maria Alvarez, RVT",
  "Devon Carter, RDCS",
  "Priya Nair, RVT",
  "James Okafor, RDMS",
] as const;

export const IMAGING_CENTRAL_ULTRASOUND_TYPES: UltrasoundType[] = [
  "Carotid Duplex",
  "Echocardiogram TTE",
  "Renal Artery Doppler",
  "LE Arterial Doppler",
  "AAA Duplex",
  "LE Venous Duplex",
];

export const IMAGING_CENTRAL_STATUSES: ImagingStatus[] = [
  "Assigned",
  "In Field",
  "Uploaded",
  "Needs Review",
  "Completed",
  "No Show",
  "Reschedule Needed",
  "Cancelled",
];

export const IMAGING_CENTRAL_WORK_QUEUE: ImagingTask[] = [
  {
    id: "IMG-1001",
    patientName: "Eleanor Whitfield",
    patientMrn: "MRN-48201",
    patientDob: "1948-03-12",
    clinic: "Northgate Cardiology",
    imagingType: "Ultrasound",
    ultrasoundType: "Carotid Duplex",
    technician: "Maria Alvarez, RVT",
    appointment: "Jun 10, 2025 · 8:30 AM",
    appointmentIso: "2025-06-10",
    coverage: "Confirmed",
    status: "Assigned",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "12 min ago",
    nextAction: "Tech to begin study",
    notes: "Bilateral carotid; prior stenosis noted on left side.",
    timeline: [
      { time: "Jun 9 · 4:15 PM", label: "Assigned to Maria Alvarez" },
      { time: "Jun 9 · 4:10 PM", label: "Coverage confirmed at Northgate" },
    ],
  },
  {
    id: "IMG-1002",
    patientName: "Marcus Bell",
    patientMrn: "MRN-48244",
    patientDob: "1955-09-02",
    clinic: "Northgate Cardiology",
    imagingType: "Ultrasound",
    ultrasoundType: "Echocardiogram TTE",
    technician: "Devon Carter, RDCS",
    appointment: "Jun 10, 2025 · 9:15 AM",
    appointmentIso: "2025-06-10",
    coverage: "Confirmed",
    status: "In Field",
    uploadStatus: "Pending",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "4 min ago",
    nextAction: "Awaiting upload from field",
    notes: "Routine TTE; evaluate EF and valve function.",
    timeline: [
      { time: "Jun 10 · 9:18 AM", label: "Study in progress" },
      { time: "Jun 10 · 9:00 AM", label: "Tech checked in on site" },
    ],
  },
  {
    id: "IMG-1003",
    patientName: "Sofia Ramirez",
    patientMrn: "MRN-48310",
    patientDob: "1962-11-21",
    clinic: "Summit Vascular Institute",
    imagingType: "Ultrasound",
    ultrasoundType: "Renal Artery Doppler",
    technician: "Priya Nair, RVT",
    appointment: "Jun 10, 2025 · 10:00 AM",
    appointmentIso: "2025-06-10",
    coverage: "Confirmed",
    status: "Uploaded",
    uploadStatus: "Uploaded",
    qcStatus: "In Review",
    procedureNoteStatus: "Draft",
    billingReadiness: "Pending",
    lastUpdated: "26 min ago",
    nextAction: "QC review of uploaded images",
    notes: "Doppler for suspected renal artery stenosis.",
    timeline: [
      { time: "Jun 10 · 10:42 AM", label: "Images uploaded" },
      { time: "Jun 10 · 10:05 AM", label: "Study started" },
    ],
  },
  {
    id: "IMG-1004",
    patientName: "Harold Jennings",
    patientMrn: "MRN-48356",
    patientDob: "1944-01-30",
    clinic: "Summit Vascular Institute",
    imagingType: "Ultrasound",
    ultrasoundType: "AAA Duplex",
    technician: "Priya Nair, RVT",
    appointment: "Jun 10, 2025 · 11:30 AM",
    appointmentIso: "2025-06-10",
    coverage: "Confirmed",
    status: "Needs Review",
    uploadStatus: "Uploaded",
    qcStatus: "Flagged",
    procedureNoteStatus: "Draft",
    billingReadiness: "Blocked",
    lastUpdated: "1 hr ago",
    nextAction: "Re-image distal aorta — incomplete views",
    notes: "AAA surveillance; distal segment poorly visualized.",
    timeline: [
      { time: "Jun 10 · 11:55 AM", label: "QC flagged incomplete views" },
      { time: "Jun 10 · 11:48 AM", label: "Images uploaded" },
    ],
  },
  {
    id: "IMG-1005",
    patientName: "Grace Donovan",
    patientMrn: "MRN-48402",
    patientDob: "1951-07-14",
    clinic: "Lakeside Family Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Venous Duplex",
    technician: "James Okafor, RDMS",
    appointment: "Jun 10, 2025 · 1:00 PM",
    appointmentIso: "2025-06-10",
    coverage: "Confirmed",
    status: "Completed",
    uploadStatus: "Uploaded",
    qcStatus: "Passed",
    procedureNoteStatus: "Complete",
    billingReadiness: "Ready",
    lastUpdated: "2 hr ago",
    nextAction: "Send to billing",
    notes: "Bilateral LE venous; no acute DVT identified.",
    timeline: [
      { time: "Jun 10 · 1:40 PM", label: "Procedure note completed" },
      { time: "Jun 10 · 1:25 PM", label: "QC passed" },
      { time: "Jun 10 · 1:05 PM", label: "Images uploaded" },
    ],
  },
  {
    id: "IMG-1006",
    patientName: "Theodore Pratt",
    patientMrn: "MRN-48455",
    patientDob: "1939-05-08",
    clinic: "Harbor Internal Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Arterial Doppler",
    technician: "Maria Alvarez, RVT",
    appointment: "Jun 10, 2025 · 2:15 PM",
    appointmentIso: "2025-06-10",
    coverage: "Pending",
    status: "Assigned",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "35 min ago",
    nextAction: "Confirm coverage at Harbor",
    notes: "Claudication workup; ABI ordered alongside.",
    timeline: [{ time: "Jun 10 · 8:00 AM", label: "Assigned, coverage pending" }],
  },
  {
    id: "IMG-1007",
    patientName: "Naomi Foster",
    patientMrn: "MRN-48511",
    patientDob: "1968-02-19",
    clinic: "Northgate Cardiology",
    imagingType: "Ultrasound",
    ultrasoundType: "Echocardiogram TTE",
    technician: "Devon Carter, RDCS",
    appointment: "Jun 11, 2025 · 8:45 AM",
    appointmentIso: "2025-06-11",
    coverage: "Confirmed",
    status: "Assigned",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "3 hr ago",
    nextAction: "Tech to begin study",
    notes: "Follow-up TTE post medication change.",
    timeline: [{ time: "Jun 10 · 3:00 PM", label: "Assigned to Devon Carter" }],
  },
  {
    id: "IMG-1008",
    patientName: "Wallace Kim",
    patientMrn: "MRN-48560",
    patientDob: "1957-12-03",
    clinic: "Lakeside Family Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "Carotid Duplex",
    technician: "James Okafor, RDMS",
    appointment: "Jun 11, 2025 · 10:30 AM",
    appointmentIso: "2025-06-11",
    coverage: "Gap",
    status: "Reschedule Needed",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Blocked",
    lastUpdated: "5 hr ago",
    nextAction: "No tech coverage — reschedule",
    notes: "Coverage gap at Lakeside on the 11th.",
    timeline: [{ time: "Jun 10 · 1:00 PM", label: "Coverage gap detected" }],
  },
  {
    id: "IMG-1009",
    patientName: "Beatrice Holloway",
    patientMrn: "MRN-48612",
    patientDob: "1946-08-27",
    clinic: "Summit Vascular Institute",
    imagingType: "Ultrasound",
    ultrasoundType: "AAA Duplex",
    technician: "Priya Nair, RVT",
    appointment: "Jun 11, 2025 · 11:45 AM",
    appointmentIso: "2025-06-11",
    coverage: "Confirmed",
    status: "No Show",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Blocked",
    lastUpdated: "Yesterday",
    nextAction: "Outreach to rebook",
    notes: "Patient did not arrive; left voicemail.",
    timeline: [{ time: "Jun 11 · 12:05 PM", label: "Marked no show" }],
  },
  {
    id: "IMG-1010",
    patientName: "Curtis Vance",
    patientMrn: "MRN-48677",
    patientDob: "1953-04-16",
    clinic: "Harbor Internal Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "Renal Artery Doppler",
    technician: "Maria Alvarez, RVT",
    appointment: "Jun 11, 2025 · 1:30 PM",
    appointmentIso: "2025-06-11",
    coverage: "Confirmed",
    status: "Uploaded",
    uploadStatus: "Uploaded",
    qcStatus: "In Review",
    procedureNoteStatus: "Draft",
    billingReadiness: "Pending",
    lastUpdated: "20 min ago",
    nextAction: "QC review of uploaded images",
    notes: "Resistant hypertension workup.",
    timeline: [
      { time: "Jun 11 · 2:10 PM", label: "Images uploaded" },
      { time: "Jun 11 · 1:35 PM", label: "Study started" },
    ],
  },
  {
    id: "IMG-1011",
    patientName: "Lucille Barrett",
    patientMrn: "MRN-48720",
    patientDob: "1960-10-09",
    clinic: "Northgate Cardiology",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Venous Duplex",
    technician: "Devon Carter, RDCS",
    appointment: "Jun 12, 2025 · 9:00 AM",
    appointmentIso: "2025-06-12",
    coverage: "Confirmed",
    status: "Completed",
    uploadStatus: "Uploaded",
    qcStatus: "Passed",
    procedureNoteStatus: "Complete",
    billingReadiness: "Ready",
    lastUpdated: "Yesterday",
    nextAction: "Send to billing",
    notes: "Bilateral LE venous; chronic venous insufficiency.",
    timeline: [
      { time: "Jun 12 · 9:50 AM", label: "Procedure note completed" },
      { time: "Jun 12 · 9:30 AM", label: "QC passed" },
    ],
  },
  {
    id: "IMG-1012",
    patientName: "Raymond Cho",
    patientMrn: "MRN-48788",
    patientDob: "1942-06-22",
    clinic: "Summit Vascular Institute",
    imagingType: "Ultrasound",
    ultrasoundType: "Carotid Duplex",
    technician: "Priya Nair, RVT",
    appointment: "Jun 12, 2025 · 10:15 AM",
    appointmentIso: "2025-06-12",
    coverage: "Confirmed",
    status: "In Field",
    uploadStatus: "Pending",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "8 min ago",
    nextAction: "Awaiting upload from field",
    notes: "Carotid surveillance post-endarterectomy.",
    timeline: [{ time: "Jun 12 · 10:20 AM", label: "Study in progress" }],
  },
  {
    id: "IMG-1013",
    patientName: "Patricia Nunez",
    patientMrn: "MRN-48833",
    patientDob: "1958-03-05",
    clinic: "Lakeside Family Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "Echocardiogram TTE",
    technician: "James Okafor, RDMS",
    appointment: "Jun 12, 2025 · 11:30 AM",
    appointmentIso: "2025-06-12",
    coverage: "Confirmed",
    status: "Needs Review",
    uploadStatus: "Uploaded",
    qcStatus: "Flagged",
    procedureNoteStatus: "Draft",
    billingReadiness: "Blocked",
    lastUpdated: "45 min ago",
    nextAction: "Re-acquire apical 4-chamber view",
    notes: "Limited acoustic windows; partial study.",
    timeline: [
      { time: "Jun 12 · 12:05 PM", label: "QC flagged limited views" },
      { time: "Jun 12 · 11:50 AM", label: "Images uploaded" },
    ],
  },
  {
    id: "IMG-1014",
    patientName: "Gerald Mathis",
    patientMrn: "MRN-48901",
    patientDob: "1949-09-18",
    clinic: "Harbor Internal Medicine",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Arterial Doppler",
    technician: "Maria Alvarez, RVT",
    appointment: "Jun 13, 2025 · 8:30 AM",
    appointmentIso: "2025-06-13",
    coverage: "Pending",
    status: "Assigned",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "1 hr ago",
    nextAction: "Confirm coverage at Harbor",
    notes: "Rest pain; rule out critical limb ischemia.",
    timeline: [{ time: "Jun 12 · 4:30 PM", label: "Assigned, coverage pending" }],
  },
  {
    id: "IMG-1015",
    patientName: "Yvonne Castillo",
    patientMrn: "MRN-48955",
    patientDob: "1965-12-29",
    clinic: "Northgate Cardiology",
    imagingType: "Ultrasound",
    ultrasoundType: "AAA Duplex",
    technician: "Devon Carter, RDCS",
    appointment: "Jun 13, 2025 · 10:00 AM",
    appointmentIso: "2025-06-13",
    coverage: "Confirmed",
    status: "Cancelled",
    uploadStatus: "Not Started",
    qcStatus: "Not Started",
    procedureNoteStatus: "Not Started",
    billingReadiness: "Pending",
    lastUpdated: "2 days ago",
    nextAction: "No action — cancelled by patient",
    notes: "Patient cancelled; will self-schedule later.",
    timeline: [{ time: "Jun 11 · 9:00 AM", label: "Cancelled by patient" }],
  },
  {
    id: "IMG-1016",
    patientName: "Frank Delgado",
    patientMrn: "MRN-49012",
    patientDob: "1950-02-11",
    clinic: "Summit Vascular Institute",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Venous Duplex",
    technician: "Priya Nair, RVT",
    appointment: "Jun 13, 2025 · 1:15 PM",
    appointmentIso: "2025-06-13",
    coverage: "Confirmed",
    status: "Completed",
    uploadStatus: "Uploaded",
    qcStatus: "Passed",
    procedureNoteStatus: "Complete",
    billingReadiness: "Ready",
    lastUpdated: "3 hr ago",
    nextAction: "Send to billing",
    notes: "Acute DVT ruled out; compression advised.",
    timeline: [
      { time: "Jun 13 · 2:00 PM", label: "Procedure note completed" },
      { time: "Jun 13 · 1:45 PM", label: "QC passed" },
    ],
  },
];

export const IMAGING_CENTRAL_COVERAGE_ROWS: ImagingCoverageRow[] = [
  {
    id: "COV-1",
    clinic: "Northgate Cardiology",
    technician: "Maria Alvarez, RVT",
    imagingType: "Ultrasound",
    ultrasoundType: "Carotid Duplex",
    date: "Jun 10, 2025",
    timeWindow: "8:00 AM – 12:00 PM",
    coverage: "Confirmed",
    assignedCount: 4,
    completedCount: 1,
  },
  {
    id: "COV-2",
    clinic: "Summit Vascular Institute",
    technician: "Priya Nair, RVT",
    imagingType: "Ultrasound",
    ultrasoundType: "Renal Artery Doppler",
    date: "Jun 10, 2025",
    timeWindow: "9:00 AM – 2:00 PM",
    coverage: "Confirmed",
    assignedCount: 5,
    completedCount: 2,
  },
  {
    id: "COV-3",
    clinic: "Harbor Internal Medicine",
    technician: "Maria Alvarez, RVT",
    imagingType: "Ultrasound",
    ultrasoundType: "LE Arterial Doppler",
    date: "Jun 10, 2025",
    timeWindow: "1:00 PM – 4:00 PM",
    coverage: "Pending",
    assignedCount: 2,
    completedCount: 0,
  },
  {
    id: "COV-4",
    clinic: "Lakeside Family Medicine",
    technician: "James Okafor, RDMS",
    imagingType: "Ultrasound",
    ultrasoundType: "Carotid Duplex",
    date: "Jun 11, 2025",
    timeWindow: "10:00 AM – 1:00 PM",
    coverage: "Gap",
    assignedCount: 3,
    completedCount: 0,
  },
  {
    id: "COV-5",
    clinic: "Northgate Cardiology",
    technician: "Devon Carter, RDCS",
    imagingType: "Ultrasound",
    ultrasoundType: "Echocardiogram TTE",
    date: "Jun 11, 2025",
    timeWindow: "8:00 AM – 11:00 AM",
    coverage: "Confirmed",
    assignedCount: 4,
    completedCount: 3,
  },
];

export const IMAGING_CENTRAL_TECH_ROSTER: ImagingTechnician[] = [
  {
    id: "TECH-1",
    name: "Maria Alvarez, RVT",
    assignedClinics: ["Northgate Cardiology", "Harbor Internal Medicine"],
    shift: "Mon–Fri · 7:30 AM–4:00 PM",
    phone: "(555) 204-8810 · x231",
    online: true,
    capacityToday: { booked: 6, max: 8 },
    currentAssignment: "Carotid Duplex · Northgate",
    completionRate: 96,
  },
  {
    id: "TECH-2",
    name: "Devon Carter, RDCS",
    assignedClinics: ["Northgate Cardiology", "Lakeside Family Medicine"],
    shift: "Mon–Fri · 8:00 AM–4:30 PM",
    phone: "(555) 204-8822 · x244",
    online: true,
    capacityToday: { booked: 5, max: 7 },
    currentAssignment: "Echocardiogram TTE · Northgate",
    completionRate: 94,
  },
  {
    id: "TECH-3",
    name: "Priya Nair, RVT",
    assignedClinics: ["Summit Vascular Institute"],
    shift: "Tue–Sat · 7:00 AM–3:30 PM",
    phone: "(555) 204-8835 · x258",
    online: true,
    capacityToday: { booked: 7, max: 8 },
    currentAssignment: "Renal Artery Doppler · Summit",
    completionRate: 98,
  },
  {
    id: "TECH-4",
    name: "James Okafor, RDMS",
    assignedClinics: ["Lakeside Family Medicine", "Harbor Internal Medicine"],
    shift: "Mon–Thu · 8:30 AM–5:00 PM",
    phone: "(555) 204-8849 · x266",
    online: false,
    capacityToday: { booked: 0, max: 6 },
    currentAssignment: "Off shift",
    completionRate: 91,
  },
];
