-- Migration 0039: Add patient_directory table (Batch 5b)
--
-- Creates the canonical patient identity table. One row per unique person.
-- The `plexus_id` column is auto-generated by a trigger so callers never
-- supply it. The integer `id` is the FK target for patient_screenings.
--
-- Apply BEFORE 0040 (which adds the FK column on patient_screenings).
-- Run the backfill script (scripts/backfill-patient-directory.ts) after
-- both migrations are applied and before flipping USE_PATIENT_DIRECTORY_ACTIVATION.

CREATE TABLE IF NOT EXISTS patient_directory (
  id           SERIAL PRIMARY KEY,
  plexus_id    TEXT   NOT NULL,
  mrn          TEXT,
  first_name   TEXT   NOT NULL,
  last_name    TEXT   NOT NULL,
  dob          TEXT,
  gender       TEXT,
  phone        TEXT,
  email        TEXT,
  insurance    TEXT,
  facility_id  TEXT,
  clinic_id    TEXT,
  status       TEXT   NOT NULL DEFAULT 'active',
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  updated_at   TIMESTAMP NOT NULL DEFAULT now()
);

-- Sequence that backs the PLX-XXXXXX counter.
CREATE SEQUENCE IF NOT EXISTS patient_directory_plexus_seq START 1;

-- Trigger function: fills plexus_id on INSERT when caller omits it or passes NULL/''.
CREATE OR REPLACE FUNCTION generate_plexus_id()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.plexus_id IS NULL OR NEW.plexus_id = '' THEN
    NEW.plexus_id := 'PLX-' || LPAD(nextval('patient_directory_plexus_seq')::TEXT, 6, '0');
  END IF;
  RETURN NEW;
END;
$$;

-- Attach the trigger (drop first so the migration is re-runnable).
DROP TRIGGER IF EXISTS trg_patient_directory_plexus_id ON patient_directory;
CREATE TRIGGER trg_patient_directory_plexus_id
  BEFORE INSERT ON patient_directory
  FOR EACH ROW EXECUTE FUNCTION generate_plexus_id();

-- Indexes.
CREATE UNIQUE INDEX IF NOT EXISTS patient_directory_plexus_id_idx
  ON patient_directory (plexus_id);

CREATE INDEX IF NOT EXISTS patient_directory_last_name_dob_idx
  ON patient_directory (last_name, dob);

CREATE INDEX IF NOT EXISTS patient_directory_mrn_idx
  ON patient_directory (mrn);

CREATE INDEX IF NOT EXISTS patient_directory_facility_id_idx
  ON patient_directory (facility_id);

CREATE INDEX IF NOT EXISTS patient_directory_status_idx
  ON patient_directory (status);
