// Patient Directory — canonical patient identity table (Batch 5b).
//
// One row per unique person. The `plexus_id` column is auto-generated by a
// DB trigger on insert (`PLX-000001`, `PLX-000002`, …) so callers never need
// to supply it. The integer `id` is the FK target used by `patient_screenings`.
//
// See docs/architecture/patient-directory-design.md §6 for the design
// rationale and the migration order.

import {
  sql,
  pgTable,
  serial,
  text,
  integer,
  timestamp,
  index,
  uniqueIndex,
  createInsertSchema,
  z,
} from "./_common";

export const PATIENT_DIRECTORY_STATUSES = [
  "active",
  "inactive",
  "merged",
  "deleted",
] as const;
export type PatientDirectoryStatus = typeof PATIENT_DIRECTORY_STATUSES[number];

export const patientDirectory = pgTable("patient_directory", {
  // Integer PK — used as FK target by patient_screenings.patient_directory_id.
  id: serial("id").primaryKey(),
  // Human-readable stable identifier. Auto-generated by DB trigger on insert
  // (PLX-000001, PLX-000002, …). Never null after insert.
  plexusId: text("plexus_id").notNull(),
  // Medical record number — optional, populated from the primary screening.
  mrn: text("mrn"),
  // Demographics.
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  dob: text("dob"),
  gender: text("gender"),
  phone: text("phone"),
  email: text("email"),
  insurance: text("insurance"),
  // Facility / clinic identifiers (text, matching existing facility-as-text
  // convention used throughout patient_screenings and cooldown_records).
  facilityId: text("facility_id"),
  clinicId: text("clinic_id"),
  // Lifecycle status.
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: timestamp("updated_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
  uniqueIndex("patient_directory_plexus_id_idx").on(table.plexusId),
  index("patient_directory_last_name_dob_idx").on(table.lastName, table.dob),
  index("patient_directory_mrn_idx").on(table.mrn),
  index("patient_directory_facility_id_idx").on(table.facilityId),
  index("patient_directory_status_idx").on(table.status),
]);

export const insertPatientDirectorySchema = createInsertSchema(patientDirectory).omit({
  id: true,
  plexusId: true,   // generated by DB trigger
  createdAt: true,
  updatedAt: true,
});

export type PatientDirectoryRow = typeof patientDirectory.$inferSelect;
export type InsertPatientDirectory = z.infer<typeof insertPatientDirectorySchema>;
