// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-dashboard/CalmClinical.tsx": () => import("../components/mockups/home-dashboard/CalmClinical.tsx"),
  "./components/mockups/home-dashboard/OperatorDense.tsx": () => import("../components/mockups/home-dashboard/OperatorDense.tsx"),
  "./components/mockups/home-dashboard/WarmConcierge.tsx": () => import("../components/mockups/home-dashboard/WarmConcierge.tsx")
};
