// TestGuy Robot — per-episode canonical document set + note version/diff lineage.
// Run with `npm run seed:testguy-episode-docs`. Requires DATABASE_URL.
//
// Populates patient_episode_documents (Order Note, Screening Addendum,
// Procedure Note, Consent, Screening Form, Test Report, Billing Document) for
// each service EPISODE (current + historical), plus patient_document_versions
// (AI-generated -> admin-edited -> clinician-edited -> signed) with structured
// diffs. Episode-keyed so there is zero cross-episode document leakage.
//
// Idempotent: deletes this screening's episode docs (+ cascaded versions) first.

import { eq, ilike, or, desc } from "drizzle-orm";

const NAME_VARIANTS = ["testguy robot", "test guy robot"];

type DocInput = {
  documentType: string;
  title: string;
  status: string;
  bodyText?: string;
  structuredData?: unknown;
  createdDate?: string;
  sentDate?: string;
  completedDate?: string;
  signedDate?: string;
  finalizedDate?: string;
  authorName?: string;
  completedByName?: string;
  signerName?: string;
  version?: number;
  versions?: Array<{
    version: number; authorRole: string; authorName: string; label: string;
    bodyText?: string; isSigned?: boolean; createdDate?: string;
    changes?: Array<{ field: string; action: string; before?: string | null; after?: string | null }>;
  }>;
};
type Episode = { key: string; label: string; date: string; isCurrent: boolean; docs: DocInput[] };

function screeningForm(answers: Record<string, string>, completed: boolean, date: string, by: string) {
  return {
    template: "Ancillary Pre-Test Screening",
    templateVersion: "v3.2",
    completed,
    completedDate: completed ? date : null,
    completedBy: completed ? by : null,
    questions: Object.entries(answers).map(([q, a]) => ({ question: q, answer: a })),
  };
}
function report(service: string, dos: string, result: string, impression: string) {
  return {
    service, dateOfService: dos, interpretingEntity: "Plexus Imaging Center",
    interpretingClinician: "Dr. Ali Imran, MD", status: "Final", finalizedAt: dos,
    result, impression,
  };
}
function billing(service: string, dos: string, cpt: string) {
  return {
    service, dateOfService: dos, cpt, modifier: "26",
    charge: "$420.00", payer: "Medicare", claimStatus: "Ready to submit",
    diagnosisCodes: ["I10", "E11.42"], renderingProvider: "Dr. Ali Imran, MD",
  };
}
function orderBody(service: string) {
  return `ANCILLARY ORDER — ${service}\n\nOrdering provider: Dr. Ali Imran, MD\nIndication: Clinical qualification confirmed via Plexus IQ. Medical necessity supported by the documented problem list and supporting findings.\n\nInstructions: Schedule ${service}; complete pre-test screening; verify insurance eligibility.`;
}
function consentBody(service: string) {
  return `INFORMED CONSENT — ${service}\n\nThe purpose, benefits, risks, and alternatives of ${service} were explained. The patient had the opportunity to ask questions and consents to proceed.`;
}

async function main() {
  if (!process.env.DATABASE_URL) { console.error("[seed:episode-docs] DATABASE_URL not set"); process.exit(1); }
  const { db, pool } = await import("../server/db");
  const { patientScreenings } = await import("@shared/schema/screening");
  const { patientEpisodeDocuments, patientDocumentVersions } = await import("@shared/schema/clinicalData");

  let exitCode = 0;
  try {
    const [s] = await db.select().from(patientScreenings)
      .where(or(...NAME_VARIANTS.map((n) => ilike(patientScreenings.name, n))))
      .orderBy(desc(patientScreenings.id)).limit(1);
    if (!s) { console.error("[seed:episode-docs] no TestGuy screening"); await pool.end(); process.exit(1); }
    const base = { clinicId: s.clinicId ?? null, patientScreeningId: s.id, patientName: s.name };

    await db.delete(patientEpisodeDocuments).where(eq(patientEpisodeDocuments.patientScreeningId, s.id));

    // ── Per-service episodes ──────────────────────────────────────────────
    const signedOrderVersions = (service: string, indicationBefore: string, indicationAfter: string) => ([
      { version: 1, authorRole: "plexus_iq", authorName: "Plexus IQ", label: "Generated by Plexus IQ", createdDate: "2026-08-10", bodyText: orderBody(service), changes: [] },
      { version: 2, authorRole: "admin", authorName: "Admin (M. Lopez)", label: "Admin Edited", createdDate: "2026-08-12", changes: [
        { field: "Clinical Indication", action: "modified", before: indicationBefore, after: indicationAfter },
      ] },
      { version: 3, authorRole: "clinician", authorName: "Dr. Ali Imran, MD", label: "Clinician Edited", createdDate: "2026-08-18", changes: [
        { field: "ICD-10", action: "added", before: null, after: "I73.9" },
        { field: "Medication evidence", action: "removed", before: "Atorvastatin", after: null },
      ] },
      { version: 4, authorRole: "clinician", authorName: "Dr. Ali Imran, MD", label: "Signed", isSigned: true, createdDate: "2026-08-18", changes: [] },
    ]);

    const services: Record<string, Episode[]> = {
      "BrainWave": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-08-15", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("BrainWave"), authorName: "Plexus IQ", signerName: "Dr. Ali Imran, MD", signedDate: "2026-08-14", version: 3 },
          { documentType: "screening_form", title: "Screening Form", status: "Complete", completedDate: "2026-08-14", completedByName: "Maria Lopez, PCS", structuredData: screeningForm({ "Symptoms of neuropathy?": "Yes — bilateral foot numbness", "Prior BrainWave?": "Yes, 2025-02-18", "Pregnant?": "N/A", "Anticoagulants?": "Aspirin 81mg" }, true, "2026-08-14", "Maria Lopez, PCS") },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("BrainWave"), createdDate: "2026-08-13", sentDate: "2026-08-13", signedDate: "2026-08-14", signerName: "TestGuy Robot", version: 1 },
          { documentType: "procedure_note", title: "Procedure Note", status: "Signed", bodyText: `POST-PROCEDURE NOTE — BrainWave\n\nStudy completed without complication. Autonomic and neurocognitive indices recorded. Findings documented in the final report.`, signerName: "Dr. Ali Imran, MD", signedDate: "2026-08-15", version: 2,
            versions: [
              { version: 1, authorRole: "plexus_iq", authorName: "Plexus IQ", label: "Generated by Plexus IQ", createdDate: "2026-08-15", bodyText: "POST-PROCEDURE NOTE — BrainWave\n\nStudy completed. Indices recorded.", changes: [] },
              { version: 2, authorRole: "clinician", authorName: "Dr. Ali Imran, MD", label: "Clinician Edited", createdDate: "2026-08-15", changes: [ { field: "Impression", action: "modified", before: "Study completed. Indices recorded.", after: "Study completed without complication. Autonomic and neurocognitive indices recorded; mild small-fiber involvement." } ] },
              { version: 3, authorRole: "clinician", authorName: "Dr. Ali Imran, MD", label: "Signed", isSigned: true, createdDate: "2026-08-15", changes: [] },
            ] },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2026-08-15", structuredData: report("BrainWave", "2026-08-15", "Mild small-fiber autonomic involvement; no acute abnormality.", "Findings consistent with diabetic autonomic neuropathy. Recommend continued glycemic control.") },
          { documentType: "billing_document", title: "Billing Document", status: "Generated", createdDate: "2026-08-16", structuredData: billing("BrainWave", "2026-08-15", "95921") },
        ] },
        { key: "2025", label: "2025", date: "2025-02-18", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("BrainWave"), signerName: "Dr. Ali Imran, MD", signedDate: "2025-02-15", version: 1 },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("BrainWave"), signedDate: "2025-02-17", signerName: "TestGuy Robot", version: 1 },
          { documentType: "procedure_note", title: "Procedure Note", status: "Signed", bodyText: "POST-PROCEDURE NOTE — BrainWave (2025)\n\nCompleted. See report.", signerName: "Dr. Ali Imran, MD", signedDate: "2025-02-18", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-02-18", structuredData: report("BrainWave", "2025-02-18", "Mild global slowing; no epileptiform activity.", "Stable vs prior. No acute change.") },
        ] },
        { key: "2024", label: "2024", date: "2024-02-12", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("BrainWave"), signerName: "Dr. Ali Imran, MD", signedDate: "2024-02-10", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2024-02-12", structuredData: report("BrainWave", "2024-02-12", "Normal autonomic study.", "Normal.") },
        ] },
      ],
      "Bilateral Carotid Duplex": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-08-29", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Bilateral Carotid Duplex"), authorName: "Plexus IQ", signerName: "Dr. Ali Imran, MD", signedDate: "2026-08-18", version: 4,
            versions: signedOrderVersions("Bilateral Carotid Duplex", "Peripheral arterial disease with vascular risk factors.", "Peripheral arterial disease with exertional claudication and multiple vascular risk factors.") },
          { documentType: "screening_form", title: "Screening Form", status: "Complete", completedDate: "2026-08-20", completedByName: "Maria Lopez, PCS", structuredData: screeningForm({ "Neck bruit?": "Right-sided bruit noted", "Prior carotid study?": "Yes, 2025-11-12", "Stroke/TIA history?": "No", "Anticoagulants?": "Aspirin 81mg" }, true, "2026-08-20", "Maria Lopez, PCS") },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("Bilateral Carotid Duplex"), createdDate: "2026-08-19", sentDate: "2026-08-19", signedDate: "2026-08-20", signerName: "TestGuy Robot", version: 1 },
        ] },
        { key: "2025", label: "2025", date: "2025-11-12", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Bilateral Carotid Duplex"), signerName: "Dr. Ali Imran, MD", signedDate: "2025-11-08", version: 1 },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("Bilateral Carotid Duplex"), signedDate: "2025-11-11", signerName: "TestGuy Robot", version: 1 },
          { documentType: "procedure_note", title: "Procedure Note", status: "Signed", bodyText: "POST-PROCEDURE NOTE — Carotid Duplex (2025)\n\nCompleted bilaterally. See report.", signerName: "Dr. Ali Imran, MD", signedDate: "2025-11-12", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-11-12", structuredData: report("Bilateral Carotid Duplex", "2025-11-12", "Mild bilateral plaque; <50% stenosis.", "No significant stenosis. Stable vs prior.") },
        ] },
        { key: "2024", label: "2024", date: "2024-11-20", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Bilateral Carotid Duplex"), signerName: "Dr. Ali Imran, MD", signedDate: "2024-11-16", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2024-11-20", structuredData: report("Bilateral Carotid Duplex", "2024-11-20", "Stable mild bilateral plaque.", "No significant interval change.") },
        ] },
        { key: "2023", label: "2023", date: "2023-11-14", isCurrent: false, docs: [
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2023-11-14", structuredData: report("Bilateral Carotid Duplex", "2023-11-14", "No significant stenosis.", "Normal.") },
        ] },
      ],
      "Lower Extremity Arterial Doppler": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-08-19", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Lower Extremity Arterial Doppler"), signerName: "Dr. Ali Imran, MD", signedDate: "2026-08-19", version: 1 },
          { documentType: "screening_form", title: "Screening Form", status: "Complete", completedDate: "2026-08-21", completedByName: "James Okafor, PCS", structuredData: screeningForm({ "Claudication?": "Yes — bilateral calf pain at 2 blocks", "Rest pain?": "No", "Non-healing wounds?": "No", "Smoking history?": "Former smoker, quit 2019" }, true, "2026-08-21", "James Okafor, PCS") },
          { documentType: "screening_addendum", title: "Order Screening Addendum", status: "Signed", createdDate: "2026-08-21", signedDate: "2026-08-21", signerName: "Dr. Ali Imran, MD", version: 1,
            bodyText: `ORDER SCREENING ADDENDUM — Lower Extremity Arterial Doppler\n\nContext: The signed order remains unchanged. During pre-test screening, additional clinically relevant information was identified that supplements (does not replace) the original order.\n\nScreening finding: Bilateral claudication at two blocks with a former 20-pack-year smoking history; diminished left dorsalis pedis pulse on exam.\n\nRelevance: Supports bilateral arterial evaluation with ABI at rest and post-exercise. No change to the original medical-necessity determination.` },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("Lower Extremity Arterial Doppler"), signedDate: "2026-08-21", signerName: "TestGuy Robot", version: 1 },
        ] },
        { key: "2025", label: "2025", date: "2025-09-19", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Lower Extremity Arterial Doppler"), signerName: "Dr. Ali Imran, MD", signedDate: "2025-09-15", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-09-19", structuredData: report("Lower Extremity Arterial Doppler", "2025-09-19", "Moderate PAD; reduced distal flow on the left.", "Moderate left PAD. Recommend risk-factor optimization.") },
        ] },
        { key: "2024", label: "2024", date: "2024-09-15", isCurrent: false, docs: [
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2024-09-15", structuredData: report("Lower Extremity Arterial Doppler", "2024-09-15", "Mild PAD.", "Mild disease. Surveillance.") },
        ] },
      ],
      "Echocardiogram TTE": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-09-03", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Ready to sign", bodyText: orderBody("Echocardiogram TTE"), authorName: "Plexus IQ", createdDate: "2026-08-22", version: 1 },
          { documentType: "consent", title: "Consent", status: "Sent", bodyText: consentBody("Echocardiogram TTE"), createdDate: "2026-08-22", sentDate: "2026-08-22", version: 1 },
          { documentType: "screening_form", title: "Screening Form", status: "Pending", structuredData: screeningForm({}, false, "", "") },
        ] },
        { key: "2025", label: "2025", date: "2025-08-25", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Echocardiogram TTE"), signerName: "Dr. Ayman Alhadheri, MD", signedDate: "2025-08-20", version: 1 },
          { documentType: "procedure_note", title: "Procedure Note", status: "Signed", bodyText: "POST-PROCEDURE NOTE — TTE (2025)\n\nCompleted. See report.", signerName: "Dr. Ayman Alhadheri, MD", signedDate: "2025-08-25", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-08-25", structuredData: report("Echocardiogram TTE", "2025-08-25", "EF 60-65%; mild concentric LVH; trace MR.", "Normal LV systolic function. Mild hypertensive heart disease.") },
        ] },
      ],
      "Lower Extremity Venous Duplex": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-08-24", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Needs signature", bodyText: orderBody("Lower Extremity Venous Duplex"), authorName: "Plexus IQ", createdDate: "2026-08-24", version: 1 },
          { documentType: "consent", title: "Consent", status: "Pending", bodyText: consentBody("Lower Extremity Venous Duplex"), createdDate: "2026-08-24", version: 1 },
        ] },
        { key: "2025", label: "2025", date: "2025-10-06", isCurrent: false, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("Lower Extremity Venous Duplex"), signerName: "Dr. Ali Imran, MD", signedDate: "2025-10-02", version: 1 },
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-10-06", structuredData: report("Lower Extremity Venous Duplex", "2025-10-06", "No evidence of DVT; competent valves.", "No DVT. Venous insufficiency not demonstrated.") },
        ] },
        { key: "2024", label: "2024", date: "2024-10-02", isCurrent: false, docs: [
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2024-10-02", structuredData: report("Lower Extremity Venous Duplex", "2024-10-02", "No DVT.", "Normal.") },
        ] },
      ],
      "VitalWave": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-09-05", isCurrent: true, docs: [
          { documentType: "order_note", title: "Order Note", status: "Signed", bodyText: orderBody("VitalWave"), signerName: "Dr. Ali Imran, MD", signedDate: "2026-08-20", version: 1 },
          { documentType: "consent", title: "Consent", status: "Signed", bodyText: consentBody("VitalWave"), signedDate: "2026-08-21", signerName: "TestGuy Robot", version: 1 },
          { documentType: "screening_form", title: "Screening Form", status: "In progress", structuredData: screeningForm({ "Dizziness on standing?": "Occasional", "Prior VitalWave?": "Yes, 2025-03-10" }, false, "", "") },
        ] },
        { key: "2025", label: "2025", date: "2025-03-10", isCurrent: false, docs: [
          { documentType: "test_report", title: "Test Report", status: "Final", finalizedDate: "2025-03-10", structuredData: report("VitalWave", "2025-03-10", "Borderline ABI 0.92 on the right.", "Borderline right ABI. Correlate clinically.") },
        ] },
      ],
      // Renal Artery Doppler is pending admin review — nothing generated yet
      // (honest: no documents pre-approval). It appears with an empty current
      // episode so the workflow gap is visible.
      "Renal Artery Doppler": [
        { key: "current", label: "Current Episode · Aug 2026", date: "2026-08-25", isCurrent: true, docs: [] },
      ],
    };

    let docCount = 0, verCount = 0;
    for (const [service, episodes] of Object.entries(services)) {
      let sort = 0;
      for (const ep of episodes) {
        for (const d of ep.docs) {
          const [row] = await db.insert(patientEpisodeDocuments).values({
            ...base,
            serviceType: service,
            episodeKey: ep.key,
            episodeLabel: ep.label,
            episodeDate: ep.date,
            isCurrent: ep.isCurrent,
            documentType: d.documentType,
            title: d.title,
            status: d.status,
            bodyText: d.bodyText ?? null,
            structuredData: (d.structuredData ?? null) as any,
            createdDate: d.createdDate ?? null,
            sentDate: d.sentDate ?? null,
            completedDate: d.completedDate ?? null,
            signedDate: d.signedDate ?? null,
            finalizedDate: d.finalizedDate ?? null,
            authorName: d.authorName ?? null,
            completedByName: d.completedByName ?? null,
            signerName: d.signerName ?? null,
            version: d.version ?? 1,
            sortOrder: sort++,
          } as any).returning({ id: patientEpisodeDocuments.id });
          docCount++;
          if (d.versions && d.versions.length > 0) {
            let vsort = 0;
            for (const v of d.versions) {
              await db.insert(patientDocumentVersions).values({
                episodeDocumentId: row.id,
                version: v.version,
                authorRole: v.authorRole,
                authorName: v.authorName,
                label: v.label,
                bodyText: v.bodyText ?? null,
                changes: (v.changes ?? []) as any,
                isSigned: !!v.isSigned,
                createdDate: v.createdDate ?? null,
                sortOrder: vsort++,
              } as any);
              verCount++;
            }
          }
        }
      }
      console.log(`  ${service}: ${episodes.length} episode(s)`);
    }

    console.log(`[seed:episode-docs] OK — documents=${docCount} versions=${verCount}`);
  } catch (err: any) {
    console.error("[seed:episode-docs] failed:", err);
    exitCode = 1;
  } finally {
    try { await pool.end(); } catch { /* noop */ }
  }
  process.exit(exitCode);
}

main().catch((err) => { console.error("[seed:episode-docs] unexpected failure:", err); process.exit(1); });
