// TestGuy Robot — canonical Plexus Story (patient_journey_events) timeline.
// Run with `npm run seed:testguy-story`. Requires DATABASE_URL.
//
// Seeds the full per-service operational lifecycle as canonical journey events
// so the Patient's Plexus Story renders real milestones: patient added, IQ
// started/completed, services qualified, order draft, admin review, outreach,
// scheduled, order signed, screening complete, addendum created, test complete,
// report finalized, procedure note generated, clinician edit, procedure note
// signed, billing ready. Idempotent: clears prior story-seed events first.

import { eq, and, ilike, or, desc } from "drizzle-orm";

const NAME_VARIANTS = ["testguy robot", "test guy robot"];
const SRC = "testguy_story_seed";

async function main() {
  if (!process.env.DATABASE_URL) { console.error("[seed:story] DATABASE_URL not set"); process.exit(1); }
  const { db, pool } = await import("../server/db");
  const { patientScreenings } = await import("@shared/schema/screening");
  const { patientJourneyEvents, patientExecutionCases } = await import("@shared/schema/executionCase");
  const { patientEpisodeDocuments } = await import("@shared/schema/clinicalData");

  let exitCode = 0;
  try {
    const [s] = await db.select().from(patientScreenings)
      .where(or(...NAME_VARIANTS.map((n) => ilike(patientScreenings.name, n))))
      .orderBy(desc(patientScreenings.id)).limit(1);
    if (!s) { console.error("[seed:story] no TestGuy screening"); await pool.end(); process.exit(1); }
    const [ec] = await db.select().from(patientExecutionCases)
      .where(eq(patientExecutionCases.patientScreeningId, s.id)).orderBy(desc(patientExecutionCases.id)).limit(1);

    // Idempotent: clear prior story-seed events (leave real events intact).
    await db.delete(patientJourneyEvents).where(and(
      eq(patientJourneyEvents.patientScreeningId, s.id),
      eq(patientJourneyEvents.eventSource, SRC),
    ));

    // Events optionally carry a document reference (service + doc + action).
    // At insert time these resolve to the canonical patient_episode_documents.id
    // and are stamped into metadata.episodeDocumentId so the Plexus Story can
    // deep-link to the SAME EpisodeDocViewer/diff the Notes section opens.
    // `action:"changes"` opens the version diff; default opens the document.
    // episodeKey defaults to "current".
    type Ev = { date: string; type: string; summary: string; service?: string; doc?: string; episodeKey?: string; action?: "open" | "changes" };
    const ev: Array<Ev> = [
      { date: "2026-06-10", type: "patient_added", summary: "Patient added to Plexus EHR" },
      { date: "2026-06-10", type: "iq_analysis_started", summary: "Plexus IQ analysis started" },
      { date: "2026-06-11", type: "iq_analysis_completed", summary: "Plexus IQ analysis completed — 14 clinical findings surfaced" },
      { date: "2026-06-11", type: "services_qualified", summary: "7 ancillary services qualified by Plexus IQ" },

      // BrainWave — full lifecycle through billing
      { date: "2026-06-12", type: "order_draft_created", summary: "Order draft created — BrainWave", service: "BrainWave", doc: "order_note" },
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — BrainWave" },
      { date: "2026-06-20", type: "outreach_started", summary: "Outreach started — BrainWave" },
      { date: "2026-07-15", type: "appointment_scheduled", summary: "Appointment scheduled — BrainWave (Aug 15)" },
      { date: "2026-08-14", type: "order_signed", summary: "Order signed — BrainWave (Dr. Ali Imran)", service: "BrainWave", doc: "order_note" },
      { date: "2026-08-14", type: "screening_completed", summary: "Screening completed — BrainWave", service: "BrainWave", doc: "screening_form" },
      { date: "2026-08-15", type: "test_completed", summary: "Test completed — BrainWave", service: "BrainWave", doc: "test_report" },
      { date: "2026-08-15", type: "report_finalized", summary: "Report finalized — BrainWave", service: "BrainWave", doc: "test_report" },
      { date: "2026-08-15", type: "procedure_note_generated", summary: "Procedure Note generated by Plexus IQ — BrainWave", service: "BrainWave", doc: "procedure_note" },
      { date: "2026-08-15", type: "note_edited", summary: "Clinician edited Procedure Note — BrainWave (1 change)", service: "BrainWave", doc: "procedure_note", action: "changes" },
      { date: "2026-08-15", type: "procedure_note_signed", summary: "Procedure Note signed — BrainWave (Dr. Ali Imran)", service: "BrainWave", doc: "procedure_note" },
      { date: "2026-08-16", type: "billing_ready", summary: "Billing document generated — BrainWave (claim ready)", service: "BrainWave", doc: "billing_document" },

      // Approved services — order/admin/sign milestones
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — VitalWave" },
      { date: "2026-08-20", type: "order_signed", summary: "Order signed — VitalWave", service: "VitalWave", doc: "order_note" },
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — Bilateral Carotid Duplex" },
      { date: "2026-08-12", type: "note_edited", summary: "Admin edited Order Note — Bilateral Carotid Duplex (1 change)", service: "Bilateral Carotid Duplex", doc: "order_note", action: "changes" },
      { date: "2026-08-18", type: "note_edited", summary: "Clinician edited Order Note — Bilateral Carotid Duplex (2 changes)", service: "Bilateral Carotid Duplex", doc: "order_note", action: "changes" },
      { date: "2026-08-18", type: "order_signed", summary: "Order signed — Bilateral Carotid Duplex (Dr. Ali Imran)", service: "Bilateral Carotid Duplex", doc: "order_note" },
      { date: "2026-08-20", type: "screening_completed", summary: "Screening completed — Bilateral Carotid Duplex", service: "Bilateral Carotid Duplex", doc: "screening_form" },
      { date: "2026-08-29", type: "appointment_scheduled", summary: "Appointment scheduled — Bilateral Carotid Duplex (Aug 29)" },
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — Echocardiogram TTE" },
      { date: "2026-08-22", type: "outreach_started", summary: "Outreach started — Echocardiogram TTE" },
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — Lower Extremity Arterial Doppler" },
      { date: "2026-08-19", type: "order_signed", summary: "Order signed — Lower Extremity Arterial Doppler", service: "Lower Extremity Arterial Doppler", doc: "order_note" },
      { date: "2026-08-21", type: "screening_completed", summary: "Screening completed — Lower Extremity Arterial Doppler", service: "Lower Extremity Arterial Doppler", doc: "screening_form" },
      { date: "2026-08-21", type: "addendum_created", summary: "Order Screening Addendum created — Lower Extremity Arterial Doppler", service: "Lower Extremity Arterial Doppler", doc: "screening_addendum" },
      { date: "2026-06-13", type: "admin_review_approved", summary: "Admin Review approved — Lower Extremity Venous Duplex" },

      // Renal — still awaiting review
      { date: "2026-06-12", type: "admin_review_pending", summary: "Awaiting Admin Review — Renal Artery Doppler" },
    ];

    // Resolve episode-document ids so story events can deep-link to the SAME
    // canonical documents the Notes section renders.
    const eDocs = await db.select({
      id: patientEpisodeDocuments.id,
      serviceType: patientEpisodeDocuments.serviceType,
      episodeKey: patientEpisodeDocuments.episodeKey,
      documentType: patientEpisodeDocuments.documentType,
    }).from(patientEpisodeDocuments).where(eq(patientEpisodeDocuments.patientScreeningId, s.id));
    const docIdByKey = new Map<string, number>();
    for (const d of eDocs) docIdByKey.set(`${d.serviceType}|${d.episodeKey}|${d.documentType}`, d.id);

    let n = 0, linked = 0;
    for (const e of ev) {
      let metadata: Record<string, unknown> = {};
      if (e.doc && e.service) {
        const key = `${e.service}|${e.episodeKey ?? "current"}|${e.doc}`;
        const docId = docIdByKey.get(key);
        if (docId != null) {
          metadata = {
            episodeDocumentId: docId,
            serviceType: e.service,
            documentType: e.doc,
            documentAction: e.action ?? "open",
          };
          linked++;
        } else {
          console.warn(`[seed:story] no episode doc for "${key}" (event: ${e.summary})`);
        }
      }
      await db.insert(patientJourneyEvents).values({
        patientName: s.name,
        patientDob: s.dob ?? null,
        patientScreeningId: s.id,
        executionCaseId: ec?.id ?? null,
        eventType: e.type,
        eventSource: SRC,
        actorUserId: null,
        summary: e.summary,
        metadata,
        createdAt: new Date(`${e.date}T12:00:00Z`),
      } as any);
      n++;
    }
    console.log(`[seed:story] OK — seeded ${n} journey events for screening ${s.id} (${linked} document-linked)`);
  } catch (err: any) {
    console.error("[seed:story] failed:", err);
    exitCode = 1;
  } finally {
    try { await pool.end(); } catch { /* noop */ }
  }
  process.exit(exitCode);
}

main().catch((err) => { console.error("[seed:story] unexpected failure:", err); process.exit(1); });
